import type { NextPage } from 'next';
import React, { useState, useEffect } from 'react';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css'
import Button from '@mui/material/Button';
import TextField from '@mui/material/TextField';
import SearchPage from '../src/SearchPage';
import DeveloperCard from '../src/Card';
import fetchDevelopers from '../services/languages';


const Home: NextPage = () => {
  const [val, setVal] = useState<string>("");


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to your <a href="https://nextjs.org">Favorite Developers!</a>
        </h1>


        <SearchPage />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '} Omar Ragab
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
